_type: ExprCall
args:
  - _type: ExprConcatStrings
    es:
      - _type: ExprLiteral
        value: 7
        valueType: Int
      - _type: ExprCall
        args:
          - _type: ExprCall
            args:
              - _type: ExprCall
                args:
                  - _type: ExprLiteral
                    value: 0
                    valueType: Int
                  - _type: ExprLiteral
                    value: 5
                    valueType: Int
                fun:
                  _type: ExprVar
                  value: __sub
              - _type: ExprLiteral
                value: 12
                valueType: Int
            fun:
              _type: ExprVar
              value: __mul
          - _type: ExprLiteral
            value: 3
            valueType: Int
        fun:
          _type: ExprVar
          value: __div
    isInterpolation: false
  - _type: ExprLiteral
    value: 1
    valueType: Int
fun:
  _type: ExprVar
  value: __sub
