_type: ExprList
elems:
  - _type: ExprLiteral
    value: x:x
    valueType: String
  - _type: ExprLiteral
    value: https://svn.cs.uu.nl:12443/repos/trace/trunk
    valueType: String
  - _type: ExprLiteral
    value: http://www2.mplayerhq.hu/MPlayer/releases/fonts/font-arial-iso-8859-1.tar.bz2
    valueType: String
  - _type: ExprLiteral
    value: http://losser.st-lab.cs.uu.nl/~armijn/.nix/gcc-3.3.4-static-nix.tar.gz
    valueType: String
  - _type: ExprLiteral
    value: http://fpdownload.macromedia.com/get/shockwave/flash/english/linux/7.0r25/install_flash_player_7_linux.tar.gz
    valueType: String
  - _type: ExprLiteral
    value: https://ftp5.gwdg.de/pub/linux/archlinux/extra/os/x86_64/unzip-6.0-14-x86_64.pkg.tar.zst
    valueType: String
  - _type: ExprLiteral
    value: ftp://ftp.gtk.org/pub/gtk/v1.2/gtk+-1.2.10.tar.gz
    valueType: String
