_type: ExprLet
attrs:
  or:
    _type: ExprLiteral
    value: 2
    valueType: Int
  x:
    _type: ExprLiteral
    value: 2
    valueType: Int
body:
  _type: ExprList
  elems:
    - _type: ExprSelect
      attrs:
        - add
      e:
        _type: ExprVar
        value: builtins
    - _type: ExprLiteral
      value: 1
      valueType: Int
    - _type: ExprVar
      value: x
    - _type: ExprSelect
      attrs:
        - add
      e:
        _type: ExprVar
        value: builtins
    - _type: ExprCall
      args:
        - _type: ExprVar
          value: or
      fun:
        _type: ExprLiteral
        value: 1
        valueType: Int
