warning: using or as an identifier is deprecated because it cannot be used in most places (try let or = 1; in or). Use --extra-deprecated-features or-as-identifier to disable this warning.
         at /pwd/in.nix:3:5:
              2|     x = 2;
              3|     or = 2;
               |     ^
              4| in
warning: using or as an argument is deprecated because it is parsed with the wrong precedence which may cause unexpected behavior. Use --extra-deprecated-features or-as-identifier to disable this warning.
         at /pwd/in.nix:7:24:
              6|         builtins.add 1 x
              7|         builtins.add 1 or
               |                        ^
              8|     ]
