queue_rules:
  - name: default
    merge_conditions:
      - author=renovate[bot]
      - check-success=collect
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
      method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label~=merge-queue|dependencies
    actions:
      queue: {}
