_type: ExprSet
attrs:
  services:
    _type: ExprSet
    attrs:
      httpd:
        _type: ExprSet
        attrs:
          enable:
            _type: ExprVar
            value: 'true'
        recursive: false
      ssh:
        _type: ExprSet
        attrs:
          enable:
            _type: ExprVar
            value: 'true'
          port:
            _type: ExprLiteral
            value: 123
            valueType: Int
        recursive: false
    recursive: false
recursive: false
