warning: __overrides attributes are deprecated and will be removed in the future. Use --extra-deprecated-features rec-set-overrides to silence this warning.
         at /pwd/parse-okay-rec-set-override-warning.nix:3:17:
              2|   # Should warn
              3|   { a = rec {}; a.__overrides = {}; }
               |                 ^
              4|   rec { __overrides = {}; }
warning: __overrides attributes are deprecated and will be removed in the future. Use --extra-deprecated-features rec-set-overrides to silence this warning.
         at /pwd/parse-okay-rec-set-override-warning.nix:4:9:
              3|   { a = rec {}; a.__overrides = {}; }
              4|   rec { __overrides = {}; }
               |         ^
              5|   # Should not warn: Not recursive
