_type: ExprLet
attrs:
  b:
    _type: ExprLiteral
    value: 2
    valueType: Int
  c:
    _type: ExprSet
    recursive: false
body:
  _type: ExprSet
  attrs:
    a:
      _type: ExprLiteral
      value: 1
      valueType: Int
    f:
      _type: ExprLiteral
      value: 3
      valueType: Int
  inherit:
    b:
      _type: ExprVar
      value: b
  inheritFrom:
    - attrs:
        - d
        - e
      from:
        _type: ExprVar
        value: c
  recursive: false
