{
  "_type": "ExprWith",
  "attrs": {
    "_type": "ExprSet",
    "recursive": false
  },
  "body": {
    "_type": "ExprList",
    "elems": [
      {
        "_type": "ExprVar",
        "value": "foo"
      },
      {
        "_type": "ExprLiteral",
        "value": "1",
        "valueType": "String"
      },
      {
        "_type": "ExprLiteral",
        "value": 2,
        "valueType": "Int"
      }
    ]
  }
}
