[package]
name = "lix"
edition = "2021"

[lib]
name = "lixrs"
path = "src/lib.rs"
crate-type = ["staticlib"]

[features]
default = []
unsafe_cancel_with_usr1 = []

[dependencies]
base64.workspace = true
lix-doc.path = "../lix-doc"
regex.workspace = true
rootcause.workspace=true
rustyline.workspace = true
rustyline-derive.workspace = true
serde.workspace = true
toml.workspace = true
rusqlite.workspace = true
nix.workspace = true
futures.workspace = true
percent-encoding.workspace = true
thiserror.workspace = true
either.workspace = true

[dev-dependencies]
temp_testdir.workspace = true
assert_matches.workspace = true
tokio = { workspace = true, features = [ "macros", "rt-multi-thread" ] }
rstest.workspace = true

[build-dependencies]
zngur.workspace = true
pkg-config.workspace = true

[lints]
workspace = true
